FROM dockerfile/java
MAINTAINER Peter Andersen <peter@sproutup.co>
ADD files /
WORKDIR /opt/docker
RUN ["chown", "-R", "daemon", "."]
USER daemon
EXPOSE 9000
ENTRYPOINT ["bin/sproutup", "-Dconfig.file=conf/application-prod.conf"]
CMD []
